name: Main
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install apt packages for Python stuff
      run: sudo apt install python3-setuptools python3-wheel
    - name: Print Python path stuff
      run: |
        echo "getsitepackages()"
        python3 -c 'import site; print(site.getsitepackages())'
        echo "sysconfig purelib"
        python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'
        echo "--user-site"
        python3 -m site --user-site
    - name: pip list
      run: |
        echo "user"
        python3 -m pip list --user
        echo "global"
        python3 -m pip list
    - name: list
      run: ls
    - name: Install pip
      run: |
        cd someModule
        python3 -m pip install .
    - name: run package
      run: |
        cd
        ls
        python3 -m pip show someModule
        echo "running"
        python3 -m someModule
