name: Main
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Install apt packages for Python stuff
      run: sudo apt install python3-setuptools python3-wheel
    - name: Print Python path stuff
      run: |
        echo "getsitepackages()"
        python3 -c 'import site; print(site.getsitepackages())'
        echo "sysconfig purelib"
        python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'
        echo "--user-site"
        python3 -m site --user-site
    - name: Install pip --user
      run: |
        cd someModule
        python3 -m pip install . --user
        cd
        python3 -m someModule
    - name: Install pip
      run: |
        cd someModule
        python3 -m pip install .
        cd
        python3 -m someModule
  macOS:
    runs-on: macos-11
    steps:
    - name: Install pip dependencies
      run: pip3 install sphinx>=3.5
    - name: pip list
      run: pip3 list -v
    - name: PATH
      run: echo $PATH
    - name: list files
      run: pip3 show -f sphinx
    - name: exechelper
      run: /usr/libexec/path_helper | sed -e 's/^PATH="//' -e 's/"; export PATH;//' | tr ":" "\n"  | tail -r
    - name: py print
      run: python3 -c 'import os,sysconfig;print(sysconfig.get_path("scripts",f"{os.name}_user"))'
    - name: py print prefix
      run: python3 -c 'import os,sysconfig;print(sysconfig.get_path("scripts",f"{os.name}_prefix"))'

